name: Build and Publish Docker Image

on:
  push:
    paths:
      - 'VERSION'  # Trigger when the VERSION file changes
    tags:
      - 'v*'       # Trigger on version tags
  workflow_dispatch:  # Allow manual triggering
    inputs:
      version:
        description: "Specify a version (optional, overrides VERSION file)"
        required: false
        default: ""
        
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Log in to Docker Hub or GitHub Container Registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extract version from the VERSION file
      - name: Read Version
        id: get_version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.DOCKERHUB_IMAGE }}:latest .
          docker tag ${{ vars.DOCKERHUB_IMAGE }}:latest ${{ vars.DOCKERHUB_IMAGE }}:${{ env.VERSION }}

      # Push the Docker image
      - name: Push Docker Image
        run: |
          docker push ${{ vars.DOCKERHUB_IMAGE }}:latest
          docker push ${{ vars.DOCKERHUB_IMAGE }}:${{ env.VERSION }}
